In [1]:
import torch

# 1 Multiple views of a storage

In [2]:
help(torch.full)

Help on built-in function full:

full(...)
    full(size, fill_value, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Creates a tensor of size :attr:`size` filled with :attr:`fill_value`. The
    tensor's dtype is inferred from :attr:`fill_value`.
    
    Args:
        size (int...): a list, tuple, or :class:`torch.Size` of integers defining the
            shape of the output tensor.
        fill_value (Scalar): the value to fill the output tensor with.
    
    Keyword args:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
     

In [33]:
M1 = torch.full((13,13), 1)

In [34]:
M1

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [35]:
M1[1,:] = 2

In [36]:
M1[:,1] = 2

In [38]:
M1

tensor([[1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [39]:
M1[6,:] = 2
M1[:,6] = 2

In [40]:
M1

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1]])

In [41]:
M1[-2,:] = 2
M1[:, -2] = 2

In [42]:
M1

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

In [43]:
M1[3:5,3:5] = 3

In [44]:
M1

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

In [45]:
M1[-5:-3,-5:-3] = 3

In [46]:
M1

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

In [47]:
M1[-5:-3,3:5] = 3

In [49]:
M1[3:5,-5:-3] = 3

In [50]:
M1

tensor([[1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 3, 3, 1, 2, 1, 3, 3, 1, 2, 1],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1]])

# 2 Eigendecomposition

In [51]:
M2 = torch.empty((20,20)).normal_()

In [52]:
M2

tensor([[-1.5132, -0.1468, -0.6762, -0.8069,  0.8709, -0.4873, -0.1080, -0.2883,
          1.5503, -1.4598, -0.6214, -0.2545, -0.4611,  0.4778, -0.2775,  1.6090,
         -1.0120,  0.8780,  0.7154, -1.6513],
        [ 0.4724,  0.5487, -1.1771,  0.7316,  0.4109, -1.6936, -0.9428,  0.0847,
         -0.5176, -0.7307,  0.6935,  1.0609,  1.0536, -1.1629, -0.7287,  0.3495,
          0.0205,  0.1041,  0.2318,  0.4573],
        [-0.3097,  1.6856,  1.2120, -1.2476,  0.6440,  0.1132,  0.9974, -1.0773,
          1.3555, -1.3442,  1.7749, -0.4374,  0.5214, -0.3502,  0.3599, -0.9537,
         -1.0971, -0.0551,  2.2685, -0.6753],
        [ 0.2616, -0.4989,  0.8576,  0.2134, -0.1510,  1.0030,  0.3836, -0.6416,
         -1.0000,  0.9143, -1.1682,  1.8007,  1.5956,  0.0319, -0.4120, -0.8811,
          1.9753, -1.3399,  0.2613, -0.8519],
        [ 0.7059, -1.1844,  1.2464,  1.1347,  0.5431,  0.2933,  1.7257, -0.7292,
         -0.9309, -0.2476, -0.9095, -0.4233,  1.4408,  0.2298, -0.3781,  0.7842,
      

In [53]:
# need the inverse

In [54]:
help(torch.inverse)

Help on built-in function inverse:

inverse(...)
    inverse(input, *, out=None) -> Tensor
    
    Takes the inverse of the square matrix :attr:`input`. :attr:`input` can be batches
    of 2D square tensors, in which case this function would return a tensor composed of
    individual inverses.
    
    .. note::
    
        Irrespective of the original strides, the returned tensors will be
        transposed, i.e. with strides like `input.contiguous().transpose(-2, -1).stride()`
    
    Args:
        input (Tensor): the input tensor of size :math:`(*, n, n)` where `*` is zero or more
                        batch dimensions
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> x = torch.rand(4, 4)
        >>> y = torch.inverse(x)
        >>> z = torch.mm(x, y)
        >>> z
        tensor([[ 1.0000, -0.0000, -0.0000,  0.0000],
                [ 0.0000,  1.0000,  0.0000,  0.0000],
                [ 0.0000,  0.0000,  1.0000,  0.0

In [58]:
# here then it makes a copy?

In [55]:
M2_inv = torch.inverse(M2)

In [56]:
M2_inv

tensor([[-3.8170e-03,  7.0653e-02,  1.2589e-01,  6.5774e-02,  6.9209e-02,
          4.8582e-03, -1.5382e-02,  1.2220e-01,  9.6284e-02,  7.2854e-02,
          1.6613e-02, -1.8632e-02,  4.1683e-02,  7.7191e-02,  7.8622e-02,
          7.0768e-02, -1.5915e-01, -6.7357e-02,  4.9481e-02,  7.4368e-02],
        [-1.8778e-01,  8.3826e-03,  1.6041e-01, -6.8975e-02, -6.2702e-02,
          5.1849e-02, -1.0736e-01,  1.5569e-01, -4.0893e-02,  9.6935e-02,
          9.4697e-02,  3.1794e-01, -8.8464e-02, -9.5372e-02,  1.6602e-01,
          2.5320e-02,  1.0876e-01, -2.4211e-01, -5.5307e-02, -6.1800e-02],
        [-1.2764e-01,  2.0478e-02, -3.9458e-02, -9.6855e-02, -4.8761e-02,
          4.9710e-03, -1.2497e-01,  2.6190e-02,  2.2757e-01, -1.3505e-01,
         -1.5195e-03,  4.3160e-01, -7.2311e-02, -5.4323e-02, -5.8926e-02,
          6.8740e-02,  1.2928e-01, -4.1007e-02,  2.6391e-02,  1.0329e-01],
        [-6.0964e-02,  6.2630e-02, -7.8493e-02, -4.3812e-02,  9.9739e-02,
         -6.4288e-02, -4.1306e-02, 

In [59]:
# now want a diagonal matrix 

In [60]:
help(torch.diag)

Help on built-in function diag:

diag(...)
    diag(input, diagonal=0, *, out=None) -> Tensor
    
    - If :attr:`input` is a vector (1-D tensor), then returns a 2-D square tensor
      with the elements of :attr:`input` as the diagonal.
    - If :attr:`input` is a matrix (2-D tensor), then returns a 1-D tensor with
      the diagonal elements of :attr:`input`.
    
    The argument :attr:`diagonal` controls which diagonal to consider:
    
    - If :attr:`diagonal` = 0, it is the main diagonal.
    - If :attr:`diagonal` > 0, it is above the main diagonal.
    - If :attr:`diagonal` < 0, it is below the main diagonal.
    
    Args:
        input (Tensor): the input tensor.
        diagonal (int, optional): the diagonal to consider
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    .. seealso::
    
            :func:`torch.diagonal` always returns the diagonal of its input.
    
            :func:`torch.diagflat` always constructs a tensor with diagonal

In [77]:
diag = torch.diag(torch.arange(20) + 1).type(torch.FloatTensor)

In [78]:
diag

tensor([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  6.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  7.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  8.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,

In [79]:
diag.shape

torch.Size([20, 20])

In [70]:
M2.shape

torch.Size([20, 20])

In [66]:
# now want to compute the product M2_inv * diag * M2

In [68]:
help(torch.mm)

Help on built-in function mm:

mm(...)
    mm(input, mat2, *, out=None) -> Tensor
    
    Performs a matrix multiplication of the matrices :attr:`input` and :attr:`mat2`.
    
    If :attr:`input` is a :math:`(n \times m)` tensor, :attr:`mat2` is a
    :math:`(m \times p)` tensor, :attr:`out` will be a :math:`(n \times p)` tensor.
    
    .. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.
              For broadcasting matrix products, see :func:`torch.matmul`.
    
    This operator supports :ref:`TensorFloat32<tf32_on_ampere>`.
    
    Args:
        input (Tensor): the first matrix to be multiplied
        mat2 (Tensor): the second matrix to be multiplied
    
    Keyword args:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> mat1 = torch.randn(2, 3)
        >>> mat2 = torch.randn(3, 3)
        >>> torch.mm(mat1, mat2)
        tensor([[ 0.4851,  0.5037, -0.3633],
                [-0.0760, -3.6705,  2.4784]])



In [72]:
# need both to be same type, so convert types to Float

In [88]:
prod = torch.mm(M2_inv, torch.mm(diag, M2))

In [89]:
prod.shape

torch.Size([20, 20])

In [90]:
# now want to get eigenvalues 

In [91]:
help(torch.eig)

Help on built-in function eig:

eig(...)
    eig(input, eigenvectors=False, *, out=None) -> (Tensor, Tensor)
    
    Computes the eigenvalues and eigenvectors of a real square matrix.
    
    .. note::
        Since eigenvalues and eigenvectors might be complex, backward pass is supported only
        for :func:`torch.symeig`
    
    Args:
        input (Tensor): the square matrix of shape :math:`(n \times n)` for which the eigenvalues and eigenvectors
            will be computed
        eigenvectors (bool): ``True`` to compute both eigenvalues and eigenvectors;
            otherwise, only eigenvalues will be computed
    
    Keyword args:
        out (tuple, optional): the output tensors
    
    Returns:
        (Tensor, Tensor): A namedtuple (eigenvalues, eigenvectors) containing
    
            - **eigenvalues** (*Tensor*): Shape :math:`(n \times 2)`. Each row is an eigenvalue of ``input``,
              where the first element is the real part and the second element is the i

In [98]:
# two columns for real and imaginary
eigvals, _ = torch.eig(prod)

In [99]:
eigvals

tensor([[ 1.0000,  0.0000],
        [20.0000,  0.0000],
        [19.0000,  0.0000],
        [ 2.0000,  0.0000],
        [ 3.0000,  0.0000],
        [ 4.0000,  0.0000],
        [ 5.0000,  0.0000],
        [ 6.0000,  0.0000],
        [18.0000,  0.0000],
        [ 7.0000,  0.0000],
        [ 8.0000,  0.0000],
        [ 9.0000,  0.0000],
        [10.0000,  0.0000],
        [17.0000,  0.0000],
        [11.0000,  0.0000],
        [12.0000,  0.0000],
        [16.0000,  0.0000],
        [15.0000,  0.0000],
        [13.0000,  0.0000],
        [14.0000,  0.0000]])

# 3 Flops per second

In [119]:
M3_1 = torch.empty((5000,5000)).normal_()

In [120]:
M3_2 = torch.empty((5000,5000)).normal_()

In [121]:
import time

In [122]:
# prod w timing 
t_start = time.perf_counter()
prod_3 = torch.mm(M3_1, M3_2)
t_end = time.perf_counter()
time_elapsed = t_end - t_start
print("time elapsed:", time_elapsed, "s")

time elapsed: 4.442264521999732 s


In [123]:
prod_3.shape

torch.Size([5000, 5000])

In [124]:
# how many floating point products have been executed per second

In [125]:
# for each element in the NxN matrix, there are (2N-1) operations

In [126]:
def get_n_operations(N):
    return (2*N-1)*N**2

In [127]:
n_op = get_n_operations(5000)

In [128]:
# per second 
n_op_per_second = n_op / time_elapsed

In [129]:
n_op_per_second

56271975422.001915

In [130]:
n_op_per_second / 1e9

56.271975422001915

56 billion ops per second

# 4 Playing with strides

In [206]:
M4 = torch.full((1000, 400), 2.0)

In [207]:
def mul_row(M):
    M_new = torch.empty((M.shape[0], M.shape[1]))
    
    # no slicing operators allowed? 
    for i in range(len(M)):
        slice_M = M[i]
        mult_M = slice_M * (i+1)
        M_new[i] = mult_M
    return M_new

In [208]:
start_time = time.perf_counter()
mul_row(M4)
end_time = time.perf_counter()
slow_time = end_time - start_time 
print("multiplication in ", slow_time, " s")

multiplication in  0.03638779099946987  s


In [209]:
# now write mul_row_fast using tensor operations 

In [210]:
def mul_row_fast(M):
    return torch.mul(torch.arange(1, M.shape[0]+1).view(M.shape[0], 1), M)

In [211]:
start_time = time.perf_counter()
mul_row_fast(M4)
end_time = time.perf_counter()
fast_time = end_time - start_time 
print("multiplication in ", fast_time, " s")

multiplication in  0.0014155260005281889  s


In [212]:
slow_mul_time / fast_time

20.42699956706213